name: Java tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java:
          - '8'
          - '11'
          - '17'

    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Eclipse Temurin ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
